Patch OpenCV to recognize MSVC 2022
Kitware/fletch pull request #715
Opened 2022-10-13 15:08 UTC by daniel-riehm

This PR adds an OpenCV runtime option for MSVC 2022, which is needed for projects which depend on OpenCV to build properly. The patch is applied to all three supported versions of OpenCV.

2022-10-13 15:08 UTC, daniel-riehm commented
jenkins test this please

2022-10-18 15:03 UTC, mleotta commented on Patches/OpenCV/4.2.0/cmake/templates/OpenCVConfig.root-WIN32.cmake.in
> +    set(OpenCV_RUNTIME vc14)
Did we lose `vc15` here intentionally?

2022-10-18 15:03 UTC, mleotta commented on Patches/OpenCV/4.5.1/cmake/templates/OpenCVConfig.root-WIN32.cmake.in
> +    set(OpenCV_RUNTIME vc14)
Same here, the previous code had a condition for `vc15`, which is now gone.

2022-10-18 15:06 UTC, mleotta requested changes
Mostly looks good, but looking at the diff in the patch it seems there are a couple of place where the code previous supported `vc15` and no longer does.  I'm not sure what version of Visual Studio `vc15` corresponds to.  Is it not needed, or was this a mistake?

2022-10-18 15:24 UTC, daniel-riehm commented
jenkins test this please

2022-10-18 20:14 UTC, daniel-riehm commented
jenkins test this please

2022-10-19 12:37 UTC, dstoup approved these changes

2022-10-19 13:32 UTC, daniel-riehm commented
jenkins test this please

2022-10-19 18:56 UTC, mleotta commented
CI errors seem unrelated.  This works for me, let's merge it.

2022-10-19 18:56 UTC, merged